### ISSUE TITLE
cant add Mapbox to the list in Google sheet

### ISSUE THREAD

**Issue by KoreTeknology** [JackDougherty/leaflet-maps-with-google-sheets#100]
Hi,
very interesting project !
i was wondering how to get all the providers in the list on the options section in the google sheet !
Can you help or there is a bug somewhere ?
Thanks
uriel

**Comment by JackDougherty** [comment]
Uriel - if you want help, insert the GitHub to your repo and explain exactly what you wish to do. I will ask one of my students to look at it.

**Comment by KoreTeknology** [comment]
Hi Jack,
i was using the demo page and try to look at the way to get Mapbox from the list of providers... without success... i see that Mapbox exist in leaflet.provider plugin, so there is no reason to not get it in the list of the sheet... Thanks if you can explain to me where i am wrong
