### ISSUE TITLE
display differences and console errors in Chrome vs FFox

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets#27]
This map does not generate any errors in FFox for Mac
https://jackdougherty.github.io/leaflet-maps-with-google-sheets/

But these problems arise in Chrome for Mac

1) Marker icons do not display properly in Chrome -- see screenshot
![interdistrict_public_schools_in_hartford_ct_and_interdistrict_public_schools_in_hartford_ct](https://cloud.githubusercontent.com/assets/649719/19485325/dc422750-9528-11e6-919d-3d55874781c1.jpg)

2) Chrome console error, probably related to above
GET https://use.fontawesome.com/a36da20aef.js net::ERR_BLOCKED_BY_CLIENT
jackdougherty.github.io/:27 

3) Chrome console warning (but I don't know if we can do anything about this one...)
Mixed Content: The page at 'https://jackdougherty.github.io/leaflet-maps-with-google-sheets/' was loaded over HTTPS, but requested an insecure image 'http://d.basemaps.cartocdn.com/light_all/11/610/761.png'. This content should also be served over HTTPS.

**Comment by JackDougherty** [comment]
@ilyankou will look at item #2 above

**Comment by JackDougherty** [comment]
Similar issue with Marker icons in legend in Chrome vs FFox
![interdistrict_public_schools_in_hartford_ct_and_interdistrict_public_schools_in_hartford_ct](https://cloud.githubusercontent.com/assets/649719/19614865/163e56e0-97c7-11e6-8758-da0425f63caf.jpg)

**Comment by ilyankou** [comment]
@JackDougherty for the image above, should Chrome be on the right?

**Comment by JackDougherty** [comment]
if this works, Jack to do: update readme
https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css
