### ISSUE TITLE
is Polygon Outline Color working correctly?

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets#29]
How can users create a point map with only a polygon outline (not color-coded)

Add "Polygon location" option = none

Add  "Polygon opacity percent" (0 to 100 percent) because sometimes users only want the outline to appear, with no filled area

Add "Polygon outline color" (default is white, but allow others to be manually set) for customization

**Comment by JackDougherty** [comment]
Thanks @ilyankou for adding the first two controls listed above, but I have a question about the third.

in Google Sheet, Polygon Outline Color = black, but display continues to be white dashed outlines

**Comment by ilyankou** [comment]
@JackDougherty 
![screen shot 2016-10-22 at 00 24 27](https://cloud.githubusercontent.com/assets/10443203/19614538/15a59d16-97ee-11e6-9fe5-53a873f9eed3.png)

**Comment by JackDougherty** [comment]
Thanks! Not sure why it took longer for this to clear up in my browser.
