### ISSUE TITLE
Map not mobile friendly with intro text

### ISSUE THREAD

**Issue by easherma** [JackDougherty/leaflet-maps-with-google-sheets#40]

**Comment by easherma** [comment]
![img_2161](https://cloud.githubusercontent.com/assets/10539855/19896339/fb5e60fa-a021-11e6-93f6-d2d3a6ebc998.PNG)

**Comment by easherma** [comment]
Can't tap on the box to close this window

**Comment by JackDougherty** [comment]
thanks for the bug report @easherma  -- we now have more funding to work on this and other helpful suggestions you made. Stay tuned!
