### ISSUE TITLE
Map Controls > Find My Location > Off -- does not work

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets#44]
When I tried selecting "off" in the Google Sheet for
Map Controls > Find My Location 

the location icon still appeared on the map

**Comment by ilyankou** [comment]
Fixed.

In `constants.js` it is `Show My Location`, whereas in the spreadsheet it is `Find My Location`. I changed it to `Show My Location` in the sheet – it works now. Careful when changing "human" names of properties!
