### ISSUE TITLE
Polygon demo is transparent

### ISSUE THREAD

**Issue by easherma** [JackDougherty/leaflet-maps-with-google-sheets#51]
Hey all,
not sure if this is intentional, but currently the polygon options in the demo seem to set polygons to transparent instead of filled in with the legend colors.

Cheers!

**Comment by JackDougherty** [comment]
@easherma - thanks for catching this, which happened while we were making updates. The polygon opacity level had been set to 0 in the Google Sheet. Now it's back to normal.
