### ISSUE TITLE
add https exception for Open Street Map

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets#63]
please fix our version of leaflet-providers for https issue in Open Street Map basemap

if working, please push code to Leaflet-Providers GitHub to see if they will accept for future

if they will not accept, in future we should rethink whether or not to use leaflet-providers, or simply rename as our own version and drop their name

**Comment by ilyankou** [comment]
`OpenStreetMap.BlackAndWhite` works fine with Google Chrome (I get no console errors about https). `MapQuestOpen` is not in `leaflet-providers.js` though.

**Comment by JackDougherty** [comment]
I'll close this after I clean up a related issue on my list
