### ISSUE TITLE
questions about custom markers

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets#72]
Would it be easy to make a custom marker appear in the legend if it is the first instance of a group?
if yes, please recommend custom marker size for me to include in readme
also tell me if .png with transparent background

For marker-color choices in the Google Sheet, should we add "none" as a logical possibility (for custom markers)?

**Comment by JackDougherty** [comment]
@ilyankou -- Should we add "none" as a possible option for marker-color choices for when users insert a custom marker? I can see both pros and cons of this, so whatever you recommend is fine with me.
![leaflet_maps_with_google_sheets_template_-_google_sheets](https://cloud.githubusercontent.com/assets/649719/21290577/99014658-c48d-11e6-8a76-31992aabf9a6.png)

**Comment by ilyankou** [comment]
In my opinion, looking for "none" is longer than leaving whatever color is selected by default, knowing that it won't affect the custom marker anyway

**Comment by JackDougherty** [comment]
Okay, I'll mention this in the notes and close this issue
