### ISSUE TITLE
Feature Suggestion: Marker Cluster Layer Support

### ISSUE THREAD

**Issue by wukkwukk** [JackDougherty/leaflet-maps-with-google-sheets#90]
Hey Jack, thanks for this awesome plugin!
I was wondering if it is possible to add this function to Leaflet Maps with Google Sheets: https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport

As I don't really have developing skills, I didn't yet manage to do it on my own.
Greets!
Malte

**Comment by JackDougherty** [comment]
Thanks @ilyankou for resolving this issue in our current dev version, to be released here as v.1 very soon
